### ISSUE TITLE
Why my colorsheme is different between Neovim and Neovem?

### ISSUE THREAD

**Issue by lissarubi** [pacha/vem#5]
I use [Dalton Theme](https://github.com/edersonferreira/dalton-vim),  and the colors are different between Neovim and Neovem. I want to know why is this occuring.

## Neovim

![Neovim](https://user-images.githubusercontent.com/54503981/112757334-67e85a80-8fb7-11eb-9c16-8da94120c13e.png)

![Neovim](https://user-images.githubusercontent.com/54503981/112757390-a67e1500-8fb7-11eb-8eb9-ddba57a0dfeb.png)

## Neovem

![Neovem](https://user-images.githubusercontent.com/54503981/112757345-79c9fd80-8fb7-11eb-8e96-187fc63f4f89.png)

![Neovem](https://user-images.githubusercontent.com/54503981/112757420-bbf33f00-8fb7-11eb-9ccf-d3660b34d148.png)

**Comment by pacha** [comment]
Hi @edersonferreira! Sorry, somehow I missed your issue until now.
This is a bit of a wild guess but it looks like you have 24bit true color enabled in Neovim but not in Vem. You can try to add:
```
set termguicolors
```
to your `vemrc` file. When true color is not enabled, the terminal tries to approximate the actual colors using a pallete of 256 fixed colors and they always look a bit off. Let me know if that doesn't work.

(Btw. you can also take a look at the [README](https://github.com/pacha/vem-dark/blob/master/README.md) file of the Vem color scheme. You don't have to use it, but it describes how to configure each one of the terminal color setups 24bit, 256 color and 16 color palletes).

**Comment by lissarubi** [comment]
Thanks! that worked fine!
