### ISSUE TITLE
How do I skip the application has requested for display host writable statusline?

### ISSUE THREAD

**Issue by MANICX100** [pacha/vem#6]

**Comment by pacha** [comment]
Hi @MANICX100,
It looks like host writable statuslines were a feature available in old vt300/vt520 DEC terminals, and that for whatever reason Vem is sending that escape sequence. Which terminal emulator are you using? :thinking:

**Comment by MANICX100** [comment]
https://flathub.org/apps/org.contourterminal.Contour

As I use neovim 
Open a new terminal document using
`flatpak run org.contourterminal.Contour nvem`

**Comment by pacha** [comment]
Ah, that explains. Contour emulates a vt525 by default.
I just pushed a fix to master. If you pull the changes, now `nvem` should start right away. Let me know if it works for you.

**Comment by MANICX100** [comment]
Sadly that didn't help.
Looking at the changes made I also tried removing any lines re: setting title, but sadly that too didn't help.

Possible debug route:
I am invoking terminal via a hotkey in icewm if that helps

**Comment by MANICX100** [comment]
> Ah, that explains. Contour emulates a vt525 by default. I just pushed a fix to master. If you pull the changes, now `nvem` should start right away. Let me know if it works for you.

That didn't help me, but I have resolved it regardless by reading the manual of Contour. I apologise as it wasn't a problem with vem, although I do not have any issue with nvim/vim/vi on its own.
 
Added display_host_writable_statusline: allow

to my Contour yml config file

[Contour Documentation](https://contour-terminal.org/configuration/profiles/#mouse:~:text=display_host_writable_statusline%20This%20option%20determines%20the%20access%20permission%20for%20displaying%20the%20%22Host%20Writable%20Statusline%22%20programmatically%20using%20the%20VT%20sequence%20DECSSDT%202.%20The%20possible%20values%20are%3A%20allow%2C%20deny%2C%20ask.)

All working now
Please revert the changes made as no longer necessary and thank you for your help :)

**Comment by pacha** [comment]
Happy to know that it is working now :)
I just run into that configuration option myself too. It seems that you can also set it to `deny`, which in the case of nvem may make more sense (the information is already in the vim/neovim statusline). But, of course, that depends on your personal preferences. I'll undo the change then :+1:

**Comment by MANICX100** [comment]
deny would make more sense. :+1: 

Thanks again
