### ISSUE TITLE
Documentation: side by side comparison of QWERTY/AZERTY/QWERTZ

### ISSUE THREAD

**Issue by Zireael07** [pacha/vem#7]
This would make it easier to compare - from a quick glance, it seems the commands are based on physical key positions, not letter mnemonics?

Would that mean vem could be adapted to e.g COLEMAK?

**Comment by pacha** [comment]
Hi @Zireael07, that's right, actions in Vem are organized based on their physical position. The issue with mnemonics is that they're only effective for a limited number of commands. When the command count increases, many commands inevitably share the same initial letter, while some letters might not be utilized at all. By disregarding mnemonics, we're free to optimize for a better typing experience, particularly for commands that are frequently used in conjunction, and to cluster commands to arrange them spatially instead (which can potentially help to remember _more_ commands than with memonics).

Regarding your suggestion for a side by side comparison of different keyboard layouts, what have you in mind? Having the diagrams of the three layouts in the same location so it is easier to spot the differences? Something like this? (of course with the names of the layouts next to each one)

![image](https://github.com/pacha/vem/assets/947817/fbb0a7b2-6d2d-4ba4-b069-ecfc8aac9ac9)
![image](https://github.com/pacha/vem/assets/947817/e03ecc71-a871-45f5-80c7-270ef2404c9b)
![image](https://github.com/pacha/vem/assets/947817/a26be966-8752-467f-96a7-aaa380a727ae)

> Would that mean vem could be adapted to e.g COLEMAK?

COLEMAK could actually work (for instance, DVORAK would definitely be more complicated). The main difficulty is to make sure that positions in QWERTY/AZERTY/QWERTZ that allow a Ctrl-key combination are allowed in the new layout. Just to give an example, COLEMAK has 'I' where QUERTY/AZERTY/QWERTZ have 'L'. Ctrl-L moves the cursor to the right in insert mode. However, Ctrl-I cannot be mapped in terminal applications for historical reasons (the application receives the TAB keycode). So long story short, it can be done but probably some compromises have to be made so it won't be the exact same experience as with the other layouts...

**Comment by Zireael07** [comment]
Yes, something like the above comment shows.

Huh, interesting about Ctrl+I not being allowed...

**Comment by pacha** [comment]
Thanks for the recommendation :) Added the comparison page to the docs:
https://www.vem-editor.org/docs/cheat-sheets/layout-comparison

> Huh, interesting about Ctrl+I not being allowed...

Yep, there are quite some historical baggage when it comes to how keys are processed by a terminal. Ctrl+I and Ctrl+M are the most important ones from the point of view of Vem, but there are others. Also, keys with only symbols can be a problem for new layouts too. If there's a swap with a letter key, that position won't accept a Ctrl combination (as that kind of combination doesn't work with symbol keys...).
